export const TRANSLATIONS: Record<string, string> = {
  dashboard: 'לוח בקרה',
  transactions: 'תנועות',
  recurring: 'הוראות קבע',
  insights: 'תובנות',
  settings: 'הגדרות',
  categories: 'ניהול קטגוריות',
  addIncome: 'הוסף הכנסה',
  addExpense: 'הוסף הוצאה',
  totalIncome: 'סה״כ הכנסות',
  totalExpenses: 'סה״כ הוצאות',
  balance: 'יתרה',
  date: 'תאריך',
  startDate: 'מתאריך',
  endDate: 'עד תאריך',
  amount: 'סכום',
  minAmount: 'סכום מינימום',
  maxAmount: 'סכום מקסימום',
  category: 'קטגוריה',
  description: 'תיאור',
  actions: 'פעולות',
  save: 'שמור',
  add: 'הוסף',
  cancel: 'ביטול',
  delete: 'מחק',
  clearAll: 'מחק הכל',
  clearAllConfirm: 'האם אתה בטוח שברצונך למחוק את כל הנתונים? פעולה זו אינה הפיכה.',
  edit: 'ערוך',
  dayOfMonth: 'יום בחודש',
  active: 'פעיל',
  generateReport: 'צור דוח',
  exportData: 'ייצוא נתונים',
  loading: 'טוען...',
  noData: 'אין נתונים זמינים',
  type: 'סוג',
  income: 'הכנסה',
  expense: 'הוצאה',
  searchPlaceholder: 'חפש לפי תיאור...',
  welcome: 'סקירה פיננסית',
  monthlyTrend: 'מגמה חודשית',
  categoryBreakdown: 'פילוח קטגוריות',
  lightMode: 'מצב יום',
  darkMode: 'מצב לילה',
  insightsPrompt: 'סקירה כללית של ההרגלים הפיננסיים שלך.',
  runRecurring: 'עבד הוראות קבע',
  quickAdd: 'הוסף תנועה חדשה',
  optional: '(אופציונלי)',
  averageMonthlyIncome: 'ממוצע הכנסה חודשי',
  averageMonthlyExpense: 'ממוצע הוצאות חודשי',
  highestExpense: 'ההוצאה הגבוהה ביותר',
  irregularExpenses: 'הוצאות חריגות',
  yearlyProjection: 'צפי שנתי',
  yearly: 'שנה',
  total: 'סה״כ',
  analysisPeriod: 'ניתוח המבוסס על הנתונים שלך',
  topCategory: 'קטגוריה מובילה בהוצאות',
  savingsRate: 'שיעור חיסכון',
  year: 'שנה',
  month: 'חודש',
  allMonths: 'כל החודשים',
  allYears: 'כל השנים',
  filter: 'סינון',
  averages: 'ממוצעים',
  update: 'עדכן',
  manageCategories: 'ניהול קטגוריות',
  newCategory: 'קטגוריה חדשה',
  categoryExists: 'קטגוריה זו כבר קיימת',
  allCategories: 'כל הקטגוריות',
  resetFilters: 'נקה סינון',
  invalidAmount: 'הסכום חייב להיות גדול מ-0',
  invalidDate: 'נא להזין תאריך תקין',
  invalidDayOfMonth: 'יום בחודש חייב להיות בין 1 ל-31',
  currentBalance: 'יתרה לתקופה',
  overdraft: 'חריגה / מינוס',
  positiveBalance: 'יתרה חיובית',
  budgetStatus: 'סטטוס',
};

export const DEFAULT_CATEGORIES = {
  INCOME: ['משכורת', 'עצמאי', 'השקעות', 'מתנות', 'אחר'],
  EXPENSE: ['מזון', 'דיור', 'תחבורה', 'חשבונות', 'בידור', 'בריאות', 'חינוך', 'קניות', 'אחר']
};

export const DEFAULT_CHART_COLORS = ['#3b82f6', '#ef4444', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899', '#6366f1'];