export const TRANSLATIONS: Record<string, string> = {
  dashboard: 'לוח בקרה',
  transactions: 'תנועות',
  recurring: 'הוראות קבע',
  insights: 'תובנות',
  settings: 'הגדרות',
  categories: 'ניהול קטגוריות',
  investments: 'השקעות',
  addIncome: 'הוסף הכנסה',
  addExpense: 'הוסף הוצאה',
  totalIncome: 'סה״כ הכנסות',
  totalExpenses: 'סה״כ הוצאות',
  balance: 'יתרה',
  date: 'תאריך',
  startDate: 'מתאריך',
  endDate: 'עד תאריך',
  amount: 'סכום',
  minAmount: 'סכום מינימום',
  maxAmount: 'סכום מקסימום',
  category: 'קטגוריה',
  description: 'תיאור',
  actions: 'פעולות',
  save: 'שמור',
  add: 'הוסף',
  cancel: 'ביטול',
  delete: 'מחק',
  clearAll: 'מחק הכל',
  clearAllConfirm: 'האם אתה בטוח שברצונך למחוק את כל הנתונים? פעולה זו אינה הפיכה.',
  edit: 'ערוך',
  dayOfMonth: 'יום בחודש',
  active: 'פעיל',
  inactive: 'לא פעיל',
  generateReport: 'צור דוח',
  exportData: 'ייצוא נתונים',
  loading: 'טוען...',
  noData: 'אין נתונים זמינים',
  type: 'סוג',
  income: 'הכנסה',
  expense: 'הוצאה',
  searchPlaceholder: 'חפש לפי תיאור...',
  welcome: 'סקירה פיננסית',
  monthlyTrend: 'מגמה חודשית',
  categoryBreakdown: 'פילוח קטגוריות',
  lightMode: 'מצב יום',
  darkMode: 'מצב לילה',
  insightsPrompt: 'סקירה כללית של ההרגלים הפיננסיים שלך.',
  runRecurring: 'עבד הוראות קבע',
  quickAdd: 'הוסף תנועה חדשה',
  optional: '(אופציונלי)',
  averageMonthlyIncome: 'ממוצע הכנסה חודשי',
  averageMonthlyExpense: 'ממוצע הוצאות חודשי',
  highestExpense: 'ההוצאה הגבוהה ביותר',
  irregularExpenses: 'הוצאות חריגות',
  yearlyProjection: 'צפי שנתי',
  yearly: 'שנה',
  total: 'סה״כ',
  analysisPeriod: 'ניתוח המבוסס על הנתונים שלך',
  topCategory: 'קטגוריה מובילה בהוצאות',
  savingsRate: 'שיעור חיסכון',
  year: 'שנה',
  month: 'חודש',
  allMonths: 'כל החודשים',
  allYears: 'כל השנים',
  filter: 'סינון',
  averages: 'ממוצעים',
  update: 'עדכן',
  manageCategories: 'ניהול קטגוריות',
  newCategory: 'קטגוריה חדשה',
  categoryExists: 'קטגוריה זו כבר קיימת',
  allCategories: 'כל הקטגוריות',
  resetFilters: 'נקה סינון',
  invalidAmount: 'הסכום חייב להיות גדול מ-0',
  invalidDate: 'נא להזין תאריך תקין',
  invalidDayOfMonth: 'יום בחודש חייב להיות בין 1 ל-31',
  currentBalance: 'יתרה לתקופה',
  overdraft: 'חריגה / מינוס',
  positiveBalance: 'יתרה חיובית',
  budgetStatus: 'סטטוס',
  actionSuccess: 'הפעולה בוצעה בהצלחה',
  actionError: 'שגיאה בביצוע הפעולה',
  dataCleared: 'כל הנתונים נמחקו בהצלחה',
  confirmDeleteTitle: 'אישור מחיקה',
  showAll: 'הצג הכל',
  currentMonth: 'חודש נוכחי',
  projectedIncome: 'הכנסה צפויה',
  projectedExpense: 'הוצאה צפויה',
  actual: 'בפועל',
  projected: 'צפי',
  dragToReorder: 'גרור לשינוי סדר',
  // Investment Translations
  assetType: 'סוג נכס',
  symbol: 'סימול / שם נכס',
  symbolPlaceholder: 'לדוגמה: AAPL או דירה בת"א',
  quantity: 'כמות',
  pricePerUnit: 'מחיר ליחידה',
  buy: 'קנייה',
  sell: 'מכירה',
  avgPrice: 'מחיר ממוצע',
  currentValue: 'שווי נוכחי',
  totalInvested: 'סה"כ הושקע',
  profit: 'רווח/הפסד',
  history: 'היסטוריה',
  shares: 'מניות/יחידות',
  addInvestment: 'הוסף פעולה',
  stock: 'מניות',
  realEstate: 'נדל"ן',
  crypto: 'קריפטו',
  other: 'אחר',
  sold: 'נמכר',
  bought: 'נקנה',
  holdings: 'החזקות',
  availableToInvest: 'זמין להשקעה',
  allocatedBudget: 'תקציב הוקצה',
  exchangeRate: 'שער חליפין (₪/$)',
  displayCurrency: 'הצג במטבע',
  groupTotal: 'סה"כ לקבוצה',
  currency: 'מטבע',
  apiKey: 'Finnhub API Key',
  apiKeyPlaceholder: 'Enter Finnhub API Key',
  refreshData: 'רענן נתונים',
  currentPrice: 'מחיר כעת',
  marketValue: 'שווי שוק',
  totalReturn: 'תשואה כוללת',
  deleteItemConfirm: 'האם למחוק פריט זה מההיסטוריה?',
  portfolioPerformance: 'ביצועי תיק',
  benchmark: 'השוואה ל-',
  timeRange: 'טווח זמן',
  range1D: 'יום',
  range5D: '5 ימים',
  range1M: 'חודש',
  range6M: '6 חודשים',
  rangeYTD: 'מתחילת השנה',
  range1Y: 'שנה',
  range3Y: '3 שנים',
  range5Y: '5 שנים',
  rangeALL: 'הכל',
  portfolio: 'תיק השקעות',
  addFunds: 'הפקד כספים',
  depositToInvestments: 'הפקדה לתיק ההשקעות',
  investedVsWorth: 'הושקע לעומת שווי',
  realizedPL: 'מומש (רווח/הפסד)',
  realizedProfit: 'רווח שמומש',
  realizedLoss: 'הפסד שמומש',
  unrealizedPL: 'על הנייר',
  costBasis: 'עלות השקעה',
  currentWorth: 'שווי נוכחי',
  netCashFlow: 'תזרים מזומנים נטו',
  sellAll: 'הכל',
};

export const DEFAULT_CATEGORIES = {
  INCOME: ['משכורת', 'עצמאי', 'מתנות', 'אחר'],
  EXPENSE: ['מזון', 'דיור', 'תחבורה', 'חשבונות', 'בידור', 'בריאות', 'חינוך', 'קניות', 'השקעה','אחר']
};

export const DEFAULT_CHART_COLORS = ['#3b82f6', '#ef4444', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899', '#6366f1'];